"""Initial migration to create detection table

Revision ID: 59cedcaad165
Revises: 
Create Date: 2024-10-22 22:25:08.057821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cedcaad165'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Only create the new detection table
    op.create_table(
        'detection',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device', sa.String(length=50), nullable=True),
        sa.Column('time_stamp', sa.String(length=100), nullable=True),
        sa.Column('latitude', sa.String(length=100), nullable=True),
        sa.Column('longitude', sa.String(length=100), nullable=True),
        sa.Column('location', sa.String(length=100), nullable=True),
        sa.Column('detection_time', sa.String(length=100), nullable=True),
        sa.Column('detection_id', sa.Integer(), nullable=True),
        sa.Column('alert_count', sa.Integer(), nullable=True),
        sa.Column('animal_type', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

def downgrade():
    # Only drop the detection table if necessary
    op.drop_table('detection')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('location',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('point', sa.NullType(), autoincrement=False, nullable=True)
    )
    op.drop_table('detection')
    # ### end Alembic commands ###
