@startuml

class deer_detected {
   +id()
   +detection_location()
   +timestamp()
   +user_location()
   +token()
   +viewed()
}

class Users {
    +name()
    +email()
    +phone()
    +alert_preference()
    +settings()
    +username()
    +password()
    +user_id()
    +user_location()
}

deer_detected --> Users: Send detected data to user

@enduml