@startuml
!define RECTANGLE class
skinparam rectangle {
    BackgroundColor #E0E0E0
    BorderColor #000000
}

RECTANGLE Requirements {
    :Gather requirements;
    :Define system requirements;
    :Create a requirements document;
}

RECTANGLE Design {
    :Figma design;
    :Create high-level architecture diagram;
    :Define database schema;
    :Develop data flow diagrams;
    :Review design with Professor;
}

RECTANGLE Implementation {
    :Set up development environment;
    :Install necessary libraries and tools into virtual machine;
    :Develop code (Python,Flutter);
    :Integrate sensors and modules onto Raspberry Pi;
    :Implement communication protocols through Flask;
    :Conduct code reviews with Professor;
}

RECTANGLE Testing {
    :Unit testing;
    :Write test cases for each module;
    :Integration testing;
    :Ensure components work together;
    :System testing;
    :Test the complete application;
    :User acceptance testing;
    :Gather feedback from users;
}

RECTANGLE Deployment {
    :Prepare deployment environment;
    :Create installation scripts;
    :Deploy to Raspberry Pi;
    :Conduct final testing in the field;
    :Document deployment process;
}

RECTANGLE Maintenance {
    :Monitor system performance;
    :Set up logging and alerting;
    :Fix bugs reported by users;
    :Implement feature updates;
    :Conduct regular reviews and improvements;

}

Requirements --> Design
Design --> Implementation
Implementation --> Testing 
Testing --> Deployment 
Deployment --> Maintenance 
Maintenance --> Requirements

@enduml