@startuml

actor Sensor
participant DetectionSystem
participant Database
actor User
actor Admin

Sensor -> DetectionSystem : detectDeer()
DetectionSystem -> Database : queryHighwayData()
Database --> DetectionSystem : returnHighwayData
DetectionSystem -> User : sendAlert (if near proximity)
Admin -> Database : updateHighwayData()

@enduml