@startuml
start
:Define System Requirements;
:Research Geofencing and Animal Detection Technologies;

:Choose Embedded Platform (Raspberry Pi);
:Select Ultrasonic Sensor for Animal Detection;

:Develop Local Geofencing Logic on Raspberry Pi;
:Integrate PostgreSQL Database for Storing Detection and Geofence Data;

:Configure Apache for Local Web Server;
:Develop Flask Backend for Data Processing;
:Develop Mobile Application with Flutter for User Alerts;


:Integrate Expo Push Notification for Mobile Alerts;

:Test Real-time Processing and Sensor Detection on Embedded Device;
:Test Data Flow to PostgreSQL Database and Mobile Application;
:Test Mobile Application for Receiving Alerts;

:Deploy System to Highway Area for Pilot Testing;
:Monitor Sensor Data and System Performance;
:Optimize Detection Accuracy and Communication Reliability;

stop
@enduml